# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgi-gaudi-service-deploy-without-rag
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgi-gaudi-service-deploy-without-rag
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: tgi-gaudi-service-deploy-without-rag
    spec:
      #      nodeSelector:
      #        demo: chatqna
      hostIPC: true
      containers:
      - envFrom:
        - configMapRef:
            name: qna-config
        env:
        - name: OMPI_MCA_btl_vader_single_copy_mechanism
          value: "none"
        - name: PT_HPU_ENABLE_LAZY_COLLECTIVES
          value: "true"
        - name: runtime
          value: "habana"
        - name: HABANA_VISIBLE_DEVICES
          value: "all"
            #- name: QUANT_CONFIG
            #value: "/data/maxabs_quant.json"
        image: tgi_gaudi:1.15.1
        name: tgi-gaudi-service-deploy-without-rag-demo
        securityContext:
          capabilities:
            add: ["SYS_NICE"]
        args:
        - --model-id
        - $(LLM_MODEL_ID)
          #- --sharded
          #- "true"
          #- --num-shard
          #- "2"
        - --max-input-tokens
        - "2048"
        - --max-total-tokens
        - "4096"
        volumeMounts:
        - mountPath: /data
          name: model-volume
        - mountPath: /dev/shm
          name: shm
        ports:
        - containerPort: 80
        resources:
          limits:
            habana.ai/gaudi: 1
              #memory: 409Gi
              #hugepages-2Mi: 95000Mi
      serviceAccountName: default
      volumes:
      - name: model-volume
        hostPath:
          # directory location on host
          #path: /mnt/models
          # this field is optional
          type: Directory
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: tgi-gaudi-without-rag-svc
spec:
  type: NodePort
  selector:
    app: tgi-gaudi-service-deploy-without-rag
  ports:
    - name: service
      port: 7979
      targetPort: 80
      nodePort: 30799
